version: '3'

networks:
  network:

services:
  nginx:
    build:
      context: docker/nginx
    working_dir: /opt/test-dev
    restart: always
    volumes:
      - .:/opt/test-dev
    ports:
      - 8000:80
    networks:
      - network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    expose:
      - 9000
    volumes:
      - .:/opt/test-dev
    networks:
      - network
    depends_on:
      - postgres

  postgres:
    image: postgres:10.4
    restart: always
    volumes:
      - .:/usr/local/pgsql
    ports:
      - 5432:5432
    networks:
      - network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test_dev
